language: c
sudo: false

compiler:
- clang
- gcc

# TODO: att OSX to matrix, currently it is too slow or whatever
#os:
#- linux
#- osx

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - check
    - cmake
    - cmake-data

# TODO: this all doesn't work by now, so I'd rather commit it and go sleep :^)

# 3 releases suggested by OpenSSL homepage as of end of 2016
#env:
#  - OPENSSL="1.1.0c"
#  - OPENSSL="1.0.2j"
#  - OPENSSL="1.0.1u"
#  - OPENSSL=""


#before_install:
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake check  ; fi

matrix:
  include:
    # Debian Jessie for all the archs possible
    # Except MIPS, they have wheezy tag only
    - env: ARCH="amd64-jessie"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="i386-jessie"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="s390x-jessie"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="arm64-jessie"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="armel-jessie"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="armhf-jessie"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="powerpc-jessie"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="mips-wheezy"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh
    - env: ARCH="mipsel-wheezy"
      compiler: gcc
      sudo: required
      script: ./.travis/cross.sh

script:
- ./.travis/build.sh

notifications:
  slack:
    secure: TJYJm44aYLmTIEFWWsnlYuWx0fCsF4gWLi/mx2WVuvzI0EcV4t3Eo5ubBMSngnODXwGk6rXV7Irvxsy2GiXGEcJd0Re7If03FtFI12VQsj7qW9SHz4a3vkz2sHaBBpCPGpW12a87p/r1b12SH+SzJUxkmwTEbffCjWzOusdtG+aEfaSyeUAILmmw+Ud9fHH6PfRqKaEZx60NWomNDcQA0ApE3oPmPM0aGCfVfoK/g3+lPmJo2zcXKTPZlgBhXc+ZK3mh13rDo9ipkKs9MLYzjwLBo7XpNU8utgtawFJ8x9EXBz8l7qPvggV8KrmWTzHh48BRxbPUTHRCLBcGim8/qBJPnpAlrxTSzkb7MtNoNoFkFfR6fTcN5PFV3JvrUpK1soDDs9YEtKXm25YHZHvgqufxETyTVqlGVyZyR/PDyXN08voV0Oxl5bxF+CnjPstp8/+Iy0t+goyf5UK707WUNHuagmvZ470iOPHTL7zGvqm4SwmimHC1i6bICGoADO4/88yJ1CMHb1tfSo4U16ipqLhNQT7AmtPtGRQo1x4Lf8avGGUATZB+RbTnGePH04zk+f+emtGbgBAh77NnJS23keplZHcZxFwLqWPAVlkIddbSk2eBz7hAIy7zPK7/emWvWU3hpT3U+Ax/4T7TLubhWSOh/ZyUNhlHWx2AD0UWqEA=
