language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    # TODO: periodically check if Travis has an up to date cmake
    # https://github.com/travis-ci/travis-ci/issues/4631#issuecomment-191153634
    sources: 
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - check
      - cmake
      - cmake-data
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make test

# TODO: construct matrix with different OpenSSL versions
# TODO: also different archs maybe?
