language: c
sudo: false

compiler: gcc

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - check
    - cmake
    - cmake-data

# Base for cross configurations
crosstemplate: &crosstemplate
  sudo: required
  services:
    - docker
  addons:
    apt:
      packages:

matrix:
  include:
    - compiler: clang
    # 3 releases suggested by OpenSSL homepage as of end of 2016
    - env: OPENSSL_VERSION="1.1.0c"
    - env: OPENSSL_VERSION="1.0.2j"
    - env: OPENSSL_VERSION="1.0.1u"
    # TODO: MIPS, it has only wheezy tags available
    # and wheezy-backports doesn't have a fresh cmake
    - env: ARCH="i386"
      <<: *crosstemplate
    - env: ARCH="s390x"
      <<: *crosstemplate
    - env: ARCH="arm64"
      <<: *crosstemplate
    - env: ARCH="armel"
      <<: *crosstemplate
    - env: ARCH="armhf"
      <<: *crosstemplate
    - env: ARCH="powerpc"
      <<: *crosstemplate
    # TODO: qemu-ppc does not support set_robust_list() syscall
    # reactivate it after the problem is solved
    #- env: ARCH="mips-wheezy"
    #  name: MIPS
    #  <<: *crosstemplate
    #- env: ARCH="mipsel-wheezy"
    #  name: MIPS Little-Endian
    #  <<: *crosstemplate
    # OSX build (can take ages to get a machine from Travis pool)
    - compiler: clang
      os: osx
      env: OPENSSL_VERSION="brew"
    - compiler: clang
      os: osx
      env: OPENSSL_VERSION="osx"
      # For some reason Apple dropped openssl headers in El Capitan
      # TODO: check 10.12
      # TODO: probably reuse libswift-migrator?
      osx_image: xcode6.4
  allow_failures:
    # PowerPC is broken atm, see #24
    - env: ARCH="powerpc"

script:
- ./.travis/build.sh

notifications:
  slack:
    secure: TJYJm44aYLmTIEFWWsnlYuWx0fCsF4gWLi/mx2WVuvzI0EcV4t3Eo5ubBMSngnODXwGk6rXV7Irvxsy2GiXGEcJd0Re7If03FtFI12VQsj7qW9SHz4a3vkz2sHaBBpCPGpW12a87p/r1b12SH+SzJUxkmwTEbffCjWzOusdtG+aEfaSyeUAILmmw+Ud9fHH6PfRqKaEZx60NWomNDcQA0ApE3oPmPM0aGCfVfoK/g3+lPmJo2zcXKTPZlgBhXc+ZK3mh13rDo9ipkKs9MLYzjwLBo7XpNU8utgtawFJ8x9EXBz8l7qPvggV8KrmWTzHh48BRxbPUTHRCLBcGim8/qBJPnpAlrxTSzkb7MtNoNoFkFfR6fTcN5PFV3JvrUpK1soDDs9YEtKXm25YHZHvgqufxETyTVqlGVyZyR/PDyXN08voV0Oxl5bxF+CnjPstp8/+Iy0t+goyf5UK707WUNHuagmvZ470iOPHTL7zGvqm4SwmimHC1i6bICGoADO4/88yJ1CMHb1tfSo4U16ipqLhNQT7AmtPtGRQo1x4Lf8avGGUATZB+RbTnGePH04zk+f+emtGbgBAh77NnJS23keplZHcZxFwLqWPAVlkIddbSk2eBz7hAIy7zPK7/emWvWU3hpT3U+Ax/4T7TLubhWSOh/ZyUNhlHWx2AD0UWqEA=
